#ifndef _ISAE_PX4_MODE_HPP_
#define _ISAE_PX4_MODE_HPP_

/* this define allow to override type generated by simulink and to use the
 * proper definition */
#define _DEFINED_TYPEDEF_FOR_PX4_MODE_

#include <cstdint>

namespace ISAE {

enum PX4_mode : std::uint8_t{
	FLAG_OFFBOARD_MODE_ENABLED = 1, /* 0b00000001 Offboard mode enabled. | */
	FLAG_ARMED = 2, /* 0b00000010 The PX4 is armed. | */
	FLAG_RC_OFFBOARD_MODE_SWITCH = 4, /* 0b00000100 Offboard switch enabled on the RC. | */
};

typedef uint8_t PX4_mode_flags;

}

#endif /* _ISAE_PX4_MODE_HPP_ */
